LU-17278 ldlm: don't grant failed lock
lock convert can re-grant lock if it loses some bits. this
procedure can race with the import's invalidation. thus
lock can become invalid (l_granted_mode=LCK_MINMODE):

  LustreError: (ldlm_lock.c:1095:ldlm_grant_lock_with_skiplist())
	ASSERTION( ldlm_is_granted(lock) )

Lustre-change: https://review.whamcloud.com/53051
Lustre-commit: f3b45a05475d8c65f06c81f41176b5a7f7d1acaa

Signed-off-by: Alex Zhuravlev <bzzz@whamcloud.com>
Change-Id: I7bb20d62948224647d7632f2822fba44d39a7713
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>
Reviewed-by: Mikhail Pershin <mpershin@whamcloud.com>